#!/usr/bin/env node
/*
 * export-overlay.js — Regenerate data/overlay.json from Firestore. NO SECRET NEEDED.
 *
 * Published submissions are public-read per firestore.rules, so this reads them via
 * the Firestore REST API using only the public web API key (the same one already in
 * js/firebase-init.js). That means the refresh loop can run anywhere — locally, in
 * CI, or in the Cloudflare Pages build — with zero credentials to manage.
 *
 * Resilient by design: on ANY error it leaves the existing overlay.json untouched
 * and exits 0, so a scheduled build is never broken by a transient Firestore hiccup.
 *
 * Usage:  node scripts/export-overlay.js        (then `npm run build`, or just `npm run refresh`)
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'data', 'overlay.json');
const INIT = path.join(ROOT, 'js', 'firebase-init.js');

// Single source of truth: pull projectId + apiKey out of firebase-init.js.
function readConfig() {
  const src = fs.readFileSync(INIT, 'utf8');
  const projectId = (src.match(/projectId:\s*["']([^"']+)["']/) || [])[1];
  const apiKey = (src.match(/apiKey:\s*["']([^"']+)["']/) || [])[1];
  return { projectId, apiKey };
}

function money(s) {
  if (s == null || s === '') return null;
  if (typeof s === 'number') return isFinite(s) ? s : null;
  const n = parseFloat(String(s).replace(/[$,\s]/g, ''));
  return isFinite(n) ? n : null;
}
function isoDay(ts) { try { const d = ts ? new Date(ts) : null; return d && !isNaN(d) ? d.toISOString().slice(0, 10) : null; } catch (e) { return null; } }
// Firestore REST wraps values as { stringValue | integerValue | doubleValue | booleanValue | ... }
function fv(x) { if (!x) return undefined; return x.stringValue ?? x.integerValue ?? x.doubleValue ?? x.booleanValue ?? undefined; }

function toReport(fields) {
  const pv = (fields.proposedValues && fields.proposedValues.mapValue && fields.proposedValues.mapValue.fields) || {};
  let entry = money(fv(pv.entry));
  const stype = String(fv(pv.salaryType) || '');
  if (entry == null && (stype === 'annual-base' || stype.indexOf('entry') !== -1)) entry = money(fv(pv.amount));
  if (entry == null) return null;
  return {
    contributorId: fv(fields.contributorId) || null,
    submittedAt: isoDay(fields.submittedAt && fields.submittedAt.timestampValue) || isoDay(Date.now()),
    entry,
    top: money(fv(pv.top)),
    hasSource: !!(fv(fields.sourceUrl) || fv(fields.sourceFile)),
    departmentMaintained: fv(fields.contributorType) === 'department'
  };
}

async function main() {
  const { projectId, apiKey } = readConfig();
  if (!projectId || !apiKey || apiKey === 'REPLACE_ME') {
    console.log('[export-overlay] Firebase not configured in firebase-init.js; leaving overlay.json unchanged.');
    return;
  }
  const url = `https://firestore.googleapis.com/v1/projects/${projectId}/databases/(default)/documents:runQuery?key=${apiKey}`;
  const body = { structuredQuery: { from: [{ collectionId: 'submissions' }], where: { fieldFilter: { field: { fieldPath: 'status' }, op: 'EQUAL', value: { stringValue: 'published' } } } } };

  const res = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  if (!res.ok) throw new Error('Firestore REST ' + res.status + ': ' + (await res.text()).slice(0, 300));
  const rows = await res.json();
  if (rows && rows.error) throw new Error(rows.error.status + ' ' + rows.error.message);

  const reports = {};
  let n = 0;
  (Array.isArray(rows) ? rows : []).forEach(r => {
    if (!r.document || !r.document.fields) return;
    const f = r.document.fields;
    const slug = fv(f.departmentSlug);
    if (!slug) return;
    const rep = toReport(f);
    if (!rep) return;
    (reports[slug] = reports[slug] || []).push(rep);
    n++;
  });

  const out = {
    generated: new Date().toISOString(),
    note: 'Auto-generated by scripts/export-overlay.js from published Firestore submissions (public read; no credentials).',
    reports
  };
  fs.writeFileSync(OUT, JSON.stringify(out, null, 2) + '\n');
  console.log(`Exported ${n} community report(s) across ${Object.keys(reports).length} department(s) -> data/overlay.json`);
}

main().catch(e => { console.error('[export-overlay] failed (keeping existing overlay.json):', e.message); process.exit(0); });
